// Nigeria States and a sample of major cities/LGAs per state.
// Used to validate `state` / `city` fields across profiles, companies and jobs.
module.exports = {
  Abia: ["Aba", "Umuahia", "Ohafia", "Arochukwu"],
  Adamawa: ["Yola", "Mubi", "Jimeta", "Numan"],
  "Akwa Ibom": ["Uyo", "Eket", "Ikot Ekpene", "Oron"],
  Anambra: ["Awka", "Onitsha", "Nnewi", "Ekwulobia"],
  Bauchi: ["Bauchi", "Azare", "Misau", "Jama'are"],
  Bayelsa: ["Yenagoa", "Brass", "Sagbama", "Ogbia"],
  Benue: ["Makurdi", "Gboko", "Otukpo", "Katsina-Ala"],
  Borno: ["Maiduguri", "Biu", "Bama", "Dikwa"],
  "Cross River": ["Calabar", "Ugep", "Ikom", "Ogoja"],
  Delta: ["Asaba", "Warri", "Sapele", "Ughelli"],
  Ebonyi: ["Abakaliki", "Afikpo", "Onueke"],
  Edo: ["Benin City", "Auchi", "Ekpoma", "Uromi"],
  Ekiti: ["Ado-Ekiti", "Ikere-Ekiti", "Oye-Ekiti"],
  Enugu: ["Enugu", "Nsukka", "Oji River", "Awgu"],
  Gombe: ["Gombe", "Kaltungo", "Billiri"],
  Imo: ["Owerri", "Orlu", "Okigwe"],
  Jigawa: ["Dutse", "Hadejia", "Gumel"],
  Kaduna: ["Kaduna", "Zaria", "Kafanchan"],
  Kano: ["Kano", "Wudil", "Gwarzo"],
  Katsina: ["Katsina", "Daura", "Funtua"],
  Kebbi: ["Birnin Kebbi", "Argungu", "Yauri"],
  Kogi: ["Lokoja", "Okene", "Idah"],
  Kwara: ["Ilorin", "Offa", "Omu-Aran"],
  Lagos: [
    "Ikeja",
    "Lagos Island",
    "Lekki",
    "Victoria Island",
    "Surulere",
    "Yaba",
    "Ikorodu",
    "Badagry",
    "Ajah",
    "Apapa",
  ],
  Nasarawa: ["Lafia", "Keffi", "Akwanga"],
  Niger: ["Minna", "Bida", "Kontagora"],
  Ogun: ["Abeokuta", "Ijebu-Ode", "Sagamu", "Ota"],
  Ondo: ["Akure", "Ondo City", "Owo"],
  Osun: ["Osogbo", "Ile-Ife", "Ilesa"],
  Oyo: ["Ibadan", "Ogbomoso", "Oyo Town"],
  Plateau: ["Jos", "Bukuru", "Pankshin"],
  Rivers: ["Port Harcourt", "Obio-Akpor", "Bonny"],
  Sokoto: ["Sokoto", "Tambuwal", "Wurno"],
  Taraba: ["Jalingo", "Wukari", "Bali"],
  Yobe: ["Damaturu", "Potiskum", "Nguru"],
  Zamfara: ["Gusau", "Kaura Namoda", "Talata Mafara"],
  FCT: ["Abuja", "Gwagwalada", "Kuje", "Bwari"],
};
